name: PR check
on: 
  push
jobs:
  build:
    env: 
      ART_NAME: 'my-artifact'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Print Variable
        uses: actions/upload-artifact
        with:
          name: ${{env.ART_NAME}}
          path: .