name: PR check
on: 
  push
jobs:
  build:
    env: 
      ART_NAME: 'my-artifact'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout repository
      
      - uses: actions/upload-artifact@v4
        name: Print Variable
      
        with:
          name: ${{env.ART_NAME}}
          path: .