name: Pipeline
on:
  push:
    branches:
      - main
jobs:    
  run_code:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run Application
      run: python3 main.py

  build:
    needs: [run_code]
    env: 
      ART_NAME: 'my-artifact'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout repository
      
      - uses: actions/upload-artifact@v4
        name: Upload Artifact
      
        with:
          name: ${{env.ART_NAME}}
          path: .